# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /c/Users/mihail.croitor/Documents/repos/miners

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /c/Users/mihail.croitor/Documents/repos/miners

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/mihail.croitor/Documents/repos/miners/CMakeFiles /c/Users/mihail.croitor/Documents/repos/miners//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/mihail.croitor/Documents/repos/miners/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Miners

# Build rule for target.
Miners: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Miners
.PHONY : Miners

# fast build rule for target.
Miners/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/build
.PHONY : Miners/fast

engine/asteroid_map.o: engine/asteroid_map.cpp.o
.PHONY : engine/asteroid_map.o

# target to build an object file
engine/asteroid_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/asteroid_map.cpp.o
.PHONY : engine/asteroid_map.cpp.o

engine/asteroid_map.i: engine/asteroid_map.cpp.i
.PHONY : engine/asteroid_map.i

# target to preprocess a source file
engine/asteroid_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/asteroid_map.cpp.i
.PHONY : engine/asteroid_map.cpp.i

engine/asteroid_map.s: engine/asteroid_map.cpp.s
.PHONY : engine/asteroid_map.s

# target to generate assembly for a file
engine/asteroid_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/asteroid_map.cpp.s
.PHONY : engine/asteroid_map.cpp.s

engine/base.o: engine/base.cpp.o
.PHONY : engine/base.o

# target to build an object file
engine/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/base.cpp.o
.PHONY : engine/base.cpp.o

engine/base.i: engine/base.cpp.i
.PHONY : engine/base.i

# target to preprocess a source file
engine/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/base.cpp.i
.PHONY : engine/base.cpp.i

engine/base.s: engine/base.cpp.s
.PHONY : engine/base.s

# target to generate assembly for a file
engine/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/base.cpp.s
.PHONY : engine/base.cpp.s

engine/game_engine.o: engine/game_engine.cpp.o
.PHONY : engine/game_engine.o

# target to build an object file
engine/game_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/game_engine.cpp.o
.PHONY : engine/game_engine.cpp.o

engine/game_engine.i: engine/game_engine.cpp.i
.PHONY : engine/game_engine.i

# target to preprocess a source file
engine/game_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/game_engine.cpp.i
.PHONY : engine/game_engine.cpp.i

engine/game_engine.s: engine/game_engine.cpp.s
.PHONY : engine/game_engine.s

# target to generate assembly for a file
engine/game_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/game_engine.cpp.s
.PHONY : engine/game_engine.cpp.s

engine/point.o: engine/point.cpp.o
.PHONY : engine/point.o

# target to build an object file
engine/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/point.cpp.o
.PHONY : engine/point.cpp.o

engine/point.i: engine/point.cpp.i
.PHONY : engine/point.i

# target to preprocess a source file
engine/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/point.cpp.i
.PHONY : engine/point.cpp.i

engine/point.s: engine/point.cpp.s
.PHONY : engine/point.s

# target to generate assembly for a file
engine/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/point.cpp.s
.PHONY : engine/point.cpp.s

engine/resource.o: engine/resource.cpp.o
.PHONY : engine/resource.o

# target to build an object file
engine/resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/resource.cpp.o
.PHONY : engine/resource.cpp.o

engine/resource.i: engine/resource.cpp.i
.PHONY : engine/resource.i

# target to preprocess a source file
engine/resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/resource.cpp.i
.PHONY : engine/resource.cpp.i

engine/resource.s: engine/resource.cpp.s
.PHONY : engine/resource.s

# target to generate assembly for a file
engine/resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/resource.cpp.s
.PHONY : engine/resource.cpp.s

engine/robot.o: engine/robot.cpp.o
.PHONY : engine/robot.o

# target to build an object file
engine/robot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/robot.cpp.o
.PHONY : engine/robot.cpp.o

engine/robot.i: engine/robot.cpp.i
.PHONY : engine/robot.i

# target to preprocess a source file
engine/robot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/robot.cpp.i
.PHONY : engine/robot.cpp.i

engine/robot.s: engine/robot.cpp.s
.PHONY : engine/robot.s

# target to generate assembly for a file
engine/robot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/engine/robot.cpp.s
.PHONY : engine/robot.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/main.cpp.s
.PHONY : main.cpp.s

modules/biggest.o: modules/biggest.cpp.o
.PHONY : modules/biggest.o

# target to build an object file
modules/biggest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/biggest.cpp.o
.PHONY : modules/biggest.cpp.o

modules/biggest.i: modules/biggest.cpp.i
.PHONY : modules/biggest.i

# target to preprocess a source file
modules/biggest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/biggest.cpp.i
.PHONY : modules/biggest.cpp.i

modules/biggest.s: modules/biggest.cpp.s
.PHONY : modules/biggest.s

# target to generate assembly for a file
modules/biggest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/biggest.cpp.s
.PHONY : modules/biggest.cpp.s

modules/metrics.o: modules/metrics.cpp.o
.PHONY : modules/metrics.o

# target to build an object file
modules/metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/metrics.cpp.o
.PHONY : modules/metrics.cpp.o

modules/metrics.i: modules/metrics.cpp.i
.PHONY : modules/metrics.i

# target to preprocess a source file
modules/metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/metrics.cpp.i
.PHONY : modules/metrics.cpp.i

modules/metrics.s: modules/metrics.cpp.s
.PHONY : modules/metrics.s

# target to generate assembly for a file
modules/metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/metrics.cpp.s
.PHONY : modules/metrics.cpp.s

modules/minsum.o: modules/minsum.cpp.o
.PHONY : modules/minsum.o

# target to build an object file
modules/minsum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/minsum.cpp.o
.PHONY : modules/minsum.cpp.o

modules/minsum.i: modules/minsum.cpp.i
.PHONY : modules/minsum.i

# target to preprocess a source file
modules/minsum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/minsum.cpp.i
.PHONY : modules/minsum.cpp.i

modules/minsum.s: modules/minsum.cpp.s
.PHONY : modules/minsum.s

# target to generate assembly for a file
modules/minsum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/minsum.cpp.s
.PHONY : modules/minsum.cpp.s

modules/nearest.o: modules/nearest.cpp.o
.PHONY : modules/nearest.o

# target to build an object file
modules/nearest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/nearest.cpp.o
.PHONY : modules/nearest.cpp.o

modules/nearest.i: modules/nearest.cpp.i
.PHONY : modules/nearest.i

# target to preprocess a source file
modules/nearest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/nearest.cpp.i
.PHONY : modules/nearest.cpp.i

modules/nearest.s: modules/nearest.cpp.s
.PHONY : modules/nearest.s

# target to generate assembly for a file
modules/nearest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/modules/nearest.cpp.s
.PHONY : modules/nearest.cpp.s

ui/picasso/color.o: ui/picasso/color.cpp.o
.PHONY : ui/picasso/color.o

# target to build an object file
ui/picasso/color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/color.cpp.o
.PHONY : ui/picasso/color.cpp.o

ui/picasso/color.i: ui/picasso/color.cpp.i
.PHONY : ui/picasso/color.i

# target to preprocess a source file
ui/picasso/color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/color.cpp.i
.PHONY : ui/picasso/color.cpp.i

ui/picasso/color.s: ui/picasso/color.cpp.s
.PHONY : ui/picasso/color.s

# target to generate assembly for a file
ui/picasso/color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/color.cpp.s
.PHONY : ui/picasso/color.cpp.s

ui/picasso/picasso.o: ui/picasso/picasso.cpp.o
.PHONY : ui/picasso/picasso.o

# target to build an object file
ui/picasso/picasso.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/picasso.cpp.o
.PHONY : ui/picasso/picasso.cpp.o

ui/picasso/picasso.i: ui/picasso/picasso.cpp.i
.PHONY : ui/picasso/picasso.i

# target to preprocess a source file
ui/picasso/picasso.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/picasso.cpp.i
.PHONY : ui/picasso/picasso.cpp.i

ui/picasso/picasso.s: ui/picasso/picasso.cpp.s
.PHONY : ui/picasso/picasso.s

# target to generate assembly for a file
ui/picasso/picasso.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/picasso.cpp.s
.PHONY : ui/picasso/picasso.cpp.s

ui/picasso/point.o: ui/picasso/point.cpp.o
.PHONY : ui/picasso/point.o

# target to build an object file
ui/picasso/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/point.cpp.o
.PHONY : ui/picasso/point.cpp.o

ui/picasso/point.i: ui/picasso/point.cpp.i
.PHONY : ui/picasso/point.i

# target to preprocess a source file
ui/picasso/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/point.cpp.i
.PHONY : ui/picasso/point.cpp.i

ui/picasso/point.s: ui/picasso/point.cpp.s
.PHONY : ui/picasso/point.s

# target to generate assembly for a file
ui/picasso/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Miners.dir/build.make CMakeFiles/Miners.dir/ui/picasso/point.cpp.s
.PHONY : ui/picasso/point.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Miners"
	@echo "... engine/asteroid_map.o"
	@echo "... engine/asteroid_map.i"
	@echo "... engine/asteroid_map.s"
	@echo "... engine/base.o"
	@echo "... engine/base.i"
	@echo "... engine/base.s"
	@echo "... engine/game_engine.o"
	@echo "... engine/game_engine.i"
	@echo "... engine/game_engine.s"
	@echo "... engine/point.o"
	@echo "... engine/point.i"
	@echo "... engine/point.s"
	@echo "... engine/resource.o"
	@echo "... engine/resource.i"
	@echo "... engine/resource.s"
	@echo "... engine/robot.o"
	@echo "... engine/robot.i"
	@echo "... engine/robot.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules/biggest.o"
	@echo "... modules/biggest.i"
	@echo "... modules/biggest.s"
	@echo "... modules/metrics.o"
	@echo "... modules/metrics.i"
	@echo "... modules/metrics.s"
	@echo "... modules/minsum.o"
	@echo "... modules/minsum.i"
	@echo "... modules/minsum.s"
	@echo "... modules/nearest.o"
	@echo "... modules/nearest.i"
	@echo "... modules/nearest.s"
	@echo "... ui/picasso/color.o"
	@echo "... ui/picasso/color.i"
	@echo "... ui/picasso/color.s"
	@echo "... ui/picasso/picasso.o"
	@echo "... ui/picasso/picasso.i"
	@echo "... ui/picasso/picasso.s"
	@echo "... ui/picasso/point.o"
	@echo "... ui/picasso/point.i"
	@echo "... ui/picasso/point.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

